# 数据集配置
dataset:
  name: "MoNuSeg"
  image_size: 512
  num_classes: 1
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1

# 模型配置
model:
  name: "TransUNet"
  in_channels: 3
  out_channels: 1
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  num_layers: 12
  mlp_ratio: 4.0
  dropout: 0.1

# 训练配置
training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: "Adam"
  scheduler: "CosineAnnealingLR"
  loss_function: "DiceBCELoss"
  
# 数据增强配置
augmentation:
  horizontal_flip_prob: 0.5
  vertical_flip_prob: 0.5
  rotation_limit: 30
  brightness_limit: 0.2
  contrast_limit: 0.2
  gaussian_noise_var: 0.01
  elastic_transform_alpha: 1
  elastic_transform_sigma: 50

# 路径配置
paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  splits_dir: "data/splits"
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"
  results_dir: "results"

# 其他配置
misc:
  seed: 42
  num_workers: 4
  device: "cuda"
  save_freq: 10
  log_freq: 100 